logging:
  level:
    org:
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG


spring:

  application:
    name: java-learn






  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: booking-service-group
    producer:
      bootstrap-servers: localhost:9092


  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AirplaneTicket;trustServerCertificate=true
    user: sa
    password: 123
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver




  jpa:
    generate-test-data: true
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        c3p0:
          max_size: 5
        show_sql: false
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update


  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false
    #All templates for mail
    templates:
      - template-name: account-activation
        template-path: /templates/mail/account-activation.html
        subject: Account Activation

      - template-name: reset-password
        template-path: /templates/mail/reset-password.html
        subject: Password Reset

      - template-name: booking-successful
        template-path: /templates/mail/booking-successful.html
        subject: Ticket Booking



schedule-task:
  remove-cancelled-booking:
    fixed-rate: 500000000
